# Generated by Django 5.2.7 on 2025-10-25 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="linked_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_habits",
                to="habit.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("sent", "Отправлено"), ("error", "Ошибка")], max_length=10)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("habit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="habit.habit")),
            ],
        ),
    ]
